= скрипт встречи от 30/3/2024

== кружки/мастерские/студии
текущее состояние: запись в школу/студию производится по знакомым, по телефону через учителя, при записи спрашивают номер телефона и после добавляют в чат школы/студии


* студенты могут сами организовать мероприятия в своей школе/студии, при этом
** любые студенты с других школ/студий (в рамках воскресной шоклы) так же могут принимать участие в мероприятиях, проводимых школами/студиями, в которых они не состоят (т.е. не обязательно состоять в школе/студии чтобы поучавствовать в мероприятии)
* любые мероприятия необходимо анонсировать, в том числе и регулярные
* необходимо реализовать ленту новостей в разделе каждой школы/студии
** реализовать возможность публиковать локальные новости в глобальную ленту
* раздел лекций в школе со встраиваемым видео с ютуба

[plantuml]
----
@startuml
:студия: --> (занятия)
:студия: --> (мероприятия)
:студия: --> (анонсы)

@enduml
----

== заметки
* нарисовать карту местности
* лекции можно вынести на главную
** навигация по глоб.лекциям
* web-kit
* при регистрации аккаунта - по умолчанию -> записан в школу
* в мобайле только модерация, без администрирования




== расписание
сейчас:: бумажное
желаемое:: расписание в электронном виде -> заливать на сайт excel файлы -> скачать в pdf/картинкой

* виджет с расписанием
* уведомление об изменениях в расписании
* отметка о посещении занятий (до начала занятия, приду/не приду)
* напоминалка о занятии

== макеты

согласованный макет - "мишин"
// необходимо дать кодовое название

=== цвет интерфеса

[horizontal]
детское:: "коврижки" (макет, выполненный в стиле дымковской игрушки)
"царское":: зеленый (изумрудный)/золотой
другие предложенные варианты:: оранжевый/голубой/зеленый
